credentials_file = "credentials.json"
project = "csye-6225-tarun_sankhla"
vpc_delete_default_routes_on_create ="true"
vpc_routing_mode ="REGIONAL"
vpc_auto_create_subnetworks = "false"
webapp_subnetwork_ip_cidr_range ="192.168.1.0/24"
db_subnetwork_ip_cidr_range ="192.168.2.0/24"
