credentials_file = "credentials.json"
vpc_delete_default_routes_on_create ="true"
vpc_routing_mode ="REGIONAL"
vpc_auto_create_subnetworks = "false"
webapp_subnetwork_ip_cidr_range ="192.168.1.0/24"
db_subnetwork_ip_cidr_range ="192.168.2.0/24"
google_compute_region_autoscaler_max_replicas =5
google_compute_region_autoscaler_min_replicas =1
google_compute_region_autoscaler_cpu_utilization_target=0.05
region="us-east1"
google_storage_bucket_location="us-east1"
zone="us-east1-b"
vpc_region="us-east1"
boot_disk_size="70"
